### ISSUE TITLE
[LinesCounter] Substring

### ISSUE THREAD

**Issue by pavel-b-novikov** [BaranovaElizaveta/nsudotnet#1]
`str.Substring(0, 2).Equals("//")`
я за такое вот сразу готов убивать. Если в java нет нормальных методов работы со строками и нормальных сравнений - не надо переносить эти комплексы на C#

**Comment by BaranovaElizaveta** [comment]
Мне просто написать str.Substring(0, 2) == "//" ?

**Comment by pavel-b-novikov** [comment]
Вы что, издеваетесь? Зачем здесь вообще создавать новую строку substring-ом?

**Comment by BaranovaElizaveta** [comment]
Пофикшено

**Comment by pavel-b-novikov** [comment]
Бинго
