### ISSUE TITLE
[LinesCounter] Внутристроковой комментарий

### ISSUE THREAD

**Issue by pavel-b-novikov** [BaranovaElizaveta/nsudotnet#2]
Если попадется строка вид `public static /*превед*/ void Main()` то она в вашем коде не будет посчитана

**Comment by BaranovaElizaveta** [comment]
Переделано

**Comment by pavel-b-novikov** [comment]
Вы убрали Substring, но вернули этот баг.

**Comment by BaranovaElizaveta** [comment]
У меня работает

К примеру, на этом файле

/**
 * Created by Елизавета on 18.09.2015.
 */

public class /*privet*/ Constants {
    static String IBORN = "IBORN";
    static String ALIVE = "ILIVE";
    static String DEAD = "IDEAD";
    static int PORT = 4010;
}

**Comment by BaranovaElizaveta** [comment]
У меня работает в том случае, который вы указали
Я ставлю флаг нахождения в многострочном комментарии только в том случае, если строка начинается с /*
И снимаю, в случае, если строка заканчивается на */
Так что тот случай, который вы указали, у меня обрабатывается корректно

**Comment by pavel-b-novikov** [comment]
Я вам указываю на случай, когда многострочный комментарий (/_) начинается в середине строки и заканчивается (_/) так же в середине какой-то другой строки

**Comment by BaranovaElizaveta** [comment]
Исправлено
