### ISSUE TITLE
[Enigma] base64

### ISSUE THREAD

**Issue by pavel-b-novikov** [BaranovaElizaveta/nsudotnet#3]
Там русским языком написано использовать base64 для хранения ключей. а вы что пишете? ASCIIEncoding.ASCII.GetString(provider.Key)? Ну ага, щас.

**Comment by BaranovaElizaveta** [comment]
Не увидела, где конкретно это прописано.

**Comment by BaranovaElizaveta** [comment]
Вот мы сделаем 
string key = Convert.ToBase64String(provider.Key);
а потом каким образом получать нужное байтовое представление этой строки, чтобы алгоритм не ругался, что у него ключ не того размера?

**Comment by BaranovaElizaveta** [comment]
Неактуально.

**Comment by pavel-b-novikov** [comment]
Не совсем понимаю зачем вам байтовое представления _строки_. По-моему вам нужно байтовое представление _ключа_

**Comment by BaranovaElizaveta** [comment]
Исправила

**Comment by pavel-b-novikov** [comment]
```
byte[] keyArray = Convert.FromBase64String(Key);
byte[] ivArray = Convert.FromBase64String(iv);
fsKeys.Write(keyArray, 0, keyArray.Length);
fsKeys.Write(ivArray, 0, ivArray.Length);
```

А это чье?

**Comment by BaranovaElizaveta** [comment]
Мое. А что тут не так?

**Comment by pavel-b-novikov** [comment]
В том, что абсолютно непонятно что вы делаете и какого результата пытаетесь достичь

**Comment by BaranovaElizaveta** [comment]
Пишу в файл значение ключа и вектора инициализации

**Comment by pavel-b-novikov** [comment]
А значение ключа и вектор инициализации - это у вас что?

**Comment by BaranovaElizaveta** [comment]
Я пишу в файл массивы байт, полученные с помощью Convert.FromBase64String из строковых Key и iv
или вы предлагаете писать Key и iv как string?

**Comment by pavel-b-novikov** [comment]
Массивы байт, полученные с помощью Convert.FromBase64String вызванной с какими параметрами?

**Comment by BaranovaElizaveta** [comment]
https://msdn.microsoft.com/ru-ru/library/system.convert.frombase64string(v=vs.110).aspx

со String'ами

**Comment by pavel-b-novikov** [comment]
вы мне ссылку на msdn не кидайте - msdn я знаю
А строку вы откуда берете?

**Comment by BaranovaElizaveta** [comment]
Получаю с помощью
                string key = Convert.ToBase64String(provider.Key);
                string iv = Convert.ToBase64String(provider.IV);
Но нам надо же в поток писать именно байты? А их можно получить большим количеством способов, но я делаю так.

**Comment by pavel-b-novikov** [comment]
То есть вы сначала переводите массив байт в Base64, потом передаете в другой метод, где возвращаете в прежний вид и пишете в файл?
А теперь возвращаемся к первому вопросу - что вы делаете и какого результата пытаетесь достичь?

**Comment by BaranovaElizaveta** [comment]
Хорошо, это бессмысленно - гонять данные в Base64 туда-сюда
Тогда я просто сделаю так: 
string key = Convert.ToBase64String(provider.Key);
string iv = Convert.ToBase64String(provider.IV);
А потом в методе WriteKey просто запишу их как String в файл

**Comment by pavel-b-novikov** [comment]
Что и требовалось в изначальной постановке задачи

**Comment by BaranovaElizaveta** [comment]
Пофикшено
